# Generated by Django 4.2.19 on 2025-02-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='purchase_order_id',
            new_name='khalti_pidx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_token',
        ),
    ]
